services:
  - type: web
    name: project-kisinia
    env: python
    plan: free
    buildCommand: "pip install -r requirement.txt"
    startCommand: "python manage.py migrate && python manage.py runserver 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: project-kisinia.onrender.com
